export class Tenant {
    tenantId:any;
    tenantName:any;
    tenantPresentAddress:any;
    tenantPermanentAddress:any;
    phoneNo:any;
    email:any;
    ocupation:any;
    propertyId:any;
    constructor(id:any,name:any,presentAddress:any,permanentAddress:any,phoneNo:any,email:any,ocupation:any,propertyId:any){
        this.tenantId=id;
        this.tenantName=name;
        this.tenantPresentAddress=presentAddress;
        this.tenantPermanentAddress=permanentAddress;
        this.phoneNo=phoneNo;
        this.email=email;
        this.ocupation=ocupation;
        this.propertyId=propertyId;
    }
}
